/**
 * LLM Provider — interface, OpenAI implementation, and MockLLM.
 *
 * Factory function selects provider based on config.
 */

import type {
  LLMProvider,
  LLMResponse,
  ChatMessage,
  LLMCompletionOptions,
  TokenUsage,
  ProviderType,
} from '../types.ts';
import { createLogger } from '../logger.ts';

const log = createLogger('llm-provider');

// ── Mock LLM ─────────────────────────────────────────────────────

/** Deterministic canned responses based on input patterns. */
const MOCK_PATTERNS: Array<{
  match: (messages: ChatMessage[]) => boolean;
  response: (messages: ChatMessage[]) => string;
}> = [
  {
    // Lint / structural analysis requests (highest priority — "lint a wiki page" ≠ "create a wiki page")
    match: (msgs) => {
      const text = msgs.map((m) => m.content).join(' ').toLowerCase();
      return text.includes('lint') || text.includes('validate') ||
        (text.includes('check') && (text.includes('issue') || text.includes('page')));
    },
    response: () =>
      JSON.stringify({
        issues: [],
        suggestions: ['Consider adding more cross-references.'],
        score: 0.95,
      }),
  },
  {
    // Compile / wiki page generation requests
    match: (msgs) => {
      const text = msgs.map((m) => m.content).join(' ').toLowerCase();
      return text.includes('compile') || text.includes('wiki page') || text.includes('create a page');
    },
    response: (msgs) => {
      const userMsg = msgs.find((m) => m.role === 'user')?.content ?? '';
      const title = userMsg.slice(0, 50).replace(/[^a-zA-Z0-9\s]/g, '').trim() || 'Mock Page';
      return [
        '---',
        `title: "${title}"`,
        'type: source',
        'tags: [mock, compiled]',
        'sources: [mock-source.md]',
        `created: ${new Date().toISOString().split('T')[0]}`,
        `updated: ${new Date().toISOString().split('T')[0]}`,
        '---',
        '',
        `# ${title}`,
        '',
        'This is a mock-compiled wiki page generated by MockLLM.',
        '',
        'Key concepts include [[Mock Concept]] and [[Related Topic]].',
        '',
        '## Summary',
        '',
        'The document covers fundamental aspects of the subject matter.',
        'Cross-references: [[Overview]], [[Index]].',
      ].join('\n');
    },
  },
  {
    // Q&A generation requests (generate factoid / multi-hop / comparison questions)
    match: (msgs) => {
      const text = msgs.map((m) => m.content).join(' ').toLowerCase();
      return (text.includes('generate') && text.includes('question')) ||
        text.includes('factoid') || text.includes('multi-hop') || text.includes('comparison question');
    },
    response: () =>
      JSON.stringify({
        questions: [
          { question: 'What is the default configuration setting?', answer: 'The default setting is enabled with standard parameters.', difficulty: 'easy' },
          { question: 'How does the system handle high-throughput scenarios?', answer: 'The system scales horizontally and uses event batching for throughput.', difficulty: 'medium' },
        ],
      }),
  },
  {
    // RAGAS / faithfulness / relevancy / precision / recall evaluations
    match: (msgs) => {
      const text = msgs.map((m) => m.content).join(' ').toLowerCase();
      return text.includes('faithfulness') || text.includes('relevancy') ||
        text.includes('precision') || text.includes('recall') ||
        (text.includes('evaluator') && text.includes('score'));
    },
    response: () =>
      JSON.stringify({
        score: 0.82,
        explanation: 'Mock evaluation: The response demonstrates reasonable alignment with the provided context.',
      }),
  },
  {
    // Judge / evaluation requests
    match: (msgs) => {
      const text = msgs.map((m) => m.content).join(' ').toLowerCase();
      return text.includes('judge') || text.includes('evaluate') || text.includes('score');
    },
    response: () =>
      JSON.stringify({
        correctness: 0.85,
        completeness: 0.78,
        coherence: 0.92,
        citationQuality: 0.70,
        reasoning: 'Mock judge evaluation: The answer demonstrates good correctness and coherence.',
      }),
  },
  {
    // Question answering requests
    match: (msgs) => {
      const text = msgs.map((m) => m.content).join(' ').toLowerCase();
      return text.includes('answer') || text.includes('question') || text.includes('?');
    },
    response: (msgs) => {
      const question = msgs.find((m) => m.role === 'user')?.content ?? 'unknown question';
      return `Based on the compiled knowledge base, the answer to "${question.slice(0, 80)}" is: This is a mock answer generated by the MockLLM provider for testing purposes. Sources: [[Mock Source 1]], [[Mock Source 2]].`;
    },
  },
];

/** Default mock response when no pattern matches. */
function defaultMockResponse(messages: ChatMessage[]): string {
  const userContent = messages.find((m) => m.role === 'user')?.content ?? '';
  return `Mock LLM response for: "${userContent.slice(0, 100)}"`;
}

/** Estimate token count from text (rough: 1 token ≈ 4 chars). */
function estimateTokens(text: string): number {
  return Math.ceil(text.length / 4);
}

/**
 * MockLLM — deterministic LLM provider for testing.
 *
 * Returns canned responses based on input patterns.
 * Consistent outputs for the same inputs (deterministic).
 * Zero external API calls.
 */
export class MockLLM implements LLMProvider {
  readonly name = 'mock';
  private callCount = 0;
  private callLog: Array<{ messages: ChatMessage[]; response: string }> = [];

  async complete(
    messages: ChatMessage[],
    options?: LLMCompletionOptions,
  ): Promise<LLMResponse> {
    this.callCount++;

    // Find matching pattern or use default
    let responseContent: string;
    const matched = MOCK_PATTERNS.find((p) => p.match(messages));
    if (matched) {
      responseContent = matched.response(messages);
    } else {
      responseContent = defaultMockResponse(messages);
    }

    const promptText = messages.map((m) => m.content).join(' ');
    const promptTokens = estimateTokens(promptText);
    const completionTokens = estimateTokens(responseContent);

    const response: LLMResponse = {
      content: responseContent,
      tokenUsage: {
        promptTokens,
        completionTokens,
        totalTokens: promptTokens + completionTokens,
      },
      model: options?.model ?? 'mock-gpt-4o-mini',
      finishReason: 'stop',
    };

    this.callLog.push({ messages, response: responseContent });
    log.debug({ callCount: this.callCount, model: response.model }, 'MockLLM completion');

    return response;
  }

  /** Get the number of calls made to this mock. */
  getCallCount(): number {
    return this.callCount;
  }

  /** Get the full call log for assertions. */
  getCallLog(): Array<{ messages: ChatMessage[]; response: string }> {
    return [...this.callLog];
  }

  /** Reset call tracking state. */
  reset(): void {
    this.callCount = 0;
    this.callLog = [];
  }
}

// ── OpenAI LLM ───────────────────────────────────────────────────

/**
 * OpenAI LLM provider — wraps the OpenAI SDK.
 *
 * Only instantiated when LLM_PROVIDER=openai and OPENAI_API_KEY is set.
 */
export class OpenAILLM implements LLMProvider {
  readonly name = 'openai';
  private client: any; // OpenAI client (lazily imported)
  private apiKey: string;

  constructor(apiKey: string) {
    this.apiKey = apiKey;
  }

  private async getClient() {
    if (!this.client) {
      const { default: OpenAI } = await import('openai');
      this.client = new OpenAI({ apiKey: this.apiKey });
    }
    return this.client;
  }

  async complete(
    messages: ChatMessage[],
    options?: LLMCompletionOptions,
  ): Promise<LLMResponse> {
    const client = await this.getClient();
    const model = options?.model ?? 'gpt-4o-mini';

    log.info({ model, messageCount: messages.length }, 'OpenAI completion request');

    const response = await client.chat.completions.create({
      model,
      messages: messages.map((m) => ({ role: m.role, content: m.content })),
      temperature: options?.temperature ?? 0.7,
      max_tokens: options?.maxTokens,
      response_format: options?.responseFormat === 'json' ? { type: 'json_object' } : undefined,
    });

    const choice = response.choices[0];
    const usage = response.usage;

    return {
      content: choice?.message?.content ?? '',
      tokenUsage: {
        promptTokens: usage?.prompt_tokens ?? 0,
        completionTokens: usage?.completion_tokens ?? 0,
        totalTokens: usage?.total_tokens ?? 0,
      },
      model,
      finishReason: choice?.finish_reason ?? 'unknown',
    };
  }
}

// ── Factory ──────────────────────────────────────────────────────

/**
 * Create an LLM provider based on provider type.
 *
 * @param provider - 'mock' or 'openai'
 * @param apiKey - Required for 'openai' provider
 */
export function createLLMProvider(provider: ProviderType, apiKey?: string): LLMProvider {
  switch (provider) {
    case 'mock':
      return new MockLLM();
    case 'openai':
      if (!apiKey) {
        throw new Error('OPENAI_API_KEY is required for OpenAI provider');
      }
      return new OpenAILLM(apiKey);
    default:
      throw new Error(`Unknown LLM provider: ${provider}`);
  }
}
